FROM node:22-alpine AS build
WORKDIR /app

RUN corepack enable

COPY frontend/package*.json ./
COPY frontend/pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY frontend/. .

ENV NODE_ENV=production

RUN pnpm nuxt build

FROM node:22-alpine as runtime
WORKDIR /app

COPY --from=build /app/.output ./.output

ENV NODE_ENV=production
ENV PORT=3000
EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]
